import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

[scrolling]
history = 5000

[window]
dynamic_padding = true
padding = {x = 5, y = 5}

[env]
TERM = "xterm-256color"

[font]
size = 13

[font.bold]
family = "CaskaydiaMonoNerdFont"
style = "Bold"

[font.bold_italic]
family = "CaskaydiaMonoNerdFont"
style = "Bold Italic"

[font.italic]
family = "CaskaydiaMonoNerdFont"
style = "SemiBold Italic"

[font.normal]
family = "CaskaydiaMonoNerdFont"
style = "SemiBold"
